// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(GreenFixDbContext))]
    partial class GreenFixDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Evidencia", b =>
                {
                    b.Property<int>("EvidenciaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvidenciaID"));

                    b.Property<string>("ArchivoURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.Property<string>("TipoArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvidenciaID");

                    b.HasIndex("ProyectoID");

                    b.ToTable("Evidencias", (string)null);
                });

            modelBuilder.Entity("backend.Models.Inversion", b =>
                {
                    b.Property<int>("InversionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InversionID"));

                    b.Property<DateTime>("FechaInversion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("MontoInvertido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.Property<decimal>("TokensAsignados")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("InversionID");

                    b.HasIndex("ProyectoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Inversiones", (string)null);
                });

            modelBuilder.Entity("backend.Models.Milestone", b =>
                {
                    b.Property<int>("MilestoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MilestoneID"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<string>("EvidenciaURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFinVotacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicioVotacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Liberado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroMilestone")
                        .HasColumnType("int");

                    b.Property<int>("Porcentaje")
                        .HasColumnType("int");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.HasKey("MilestoneID");

                    b.HasIndex("ProyectoID");

                    b.ToTable("Milestones", (string)null);
                });

            modelBuilder.Entity("backend.Models.Pago", b =>
                {
                    b.Property<int>("PagoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoID"));

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoPago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("int");

                    b.Property<bool>("Pagado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.HasKey("PagoID");

                    b.HasIndex("ProyectoID");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("backend.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProyectoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Descripcion");

                    b.Property<int>("DuracionMeses")
                        .HasColumnType("int");

                    b.Property<int>("EmprendedorId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Funding");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Garantia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Interes")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MontoActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoObjetivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NombreProyecto");

                    b.Property<int?>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Proyectos", null, t =>
                        {
                            t.Property("UsuarioID")
                                .HasColumnName("UsuarioID1");
                        });
                });

            modelBuilder.Entity("backend.Models.Recompensa", b =>
                {
                    b.Property<int>("RecompensaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecompensaID"));

                    b.Property<DateTime?>("FechaReclamo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoGanancia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.Property<bool>("Reclamada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("RecompensaID");

                    b.HasIndex("ProyectoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Recompensas", (string)null);
                });

            modelBuilder.Entity("backend.Models.Reembolso", b =>
                {
                    b.Property<int>("ReembolsoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReembolsoID"));

                    b.Property<DateTime>("FechaReembolso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("MontoReembolso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ReembolsoID");

                    b.HasIndex("ProyectoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Reembolsos", (string)null);
                });

            modelBuilder.Entity("backend.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("backend.Models.Voto", b =>
                {
                    b.Property<int>("VotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VotoID"));

                    b.Property<DateTime>("FechaVoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("MilestoneID")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoVoto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<bool>("VotoValor")
                        .HasColumnType("bit");

                    b.HasKey("VotoID");

                    b.HasIndex("MilestoneID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Votos", (string)null);
                });

            modelBuilder.Entity("backend.Models.Evidencia", b =>
                {
                    b.HasOne("backend.Models.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Inversion", b =>
                {
                    b.HasOne("backend.Models.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Milestone", b =>
                {
                    b.HasOne("backend.Models.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Pago", b =>
                {
                    b.HasOne("backend.Models.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Proyecto", b =>
                {
                    b.HasOne("backend.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.Recompensa", b =>
                {
                    b.HasOne("backend.Models.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Reembolso", b =>
                {
                    b.HasOne("backend.Models.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Voto", b =>
                {
                    b.HasOne("backend.Models.Milestone", null)
                        .WithMany()
                        .HasForeignKey("MilestoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
